In [1]:
# write python program to create an array and perform adition of two matrices.
# using the numpy array 
import numpy as np 
Matrix_A = np.array([[[14,36,57],[28,67,87],[98,76,34]]])
print(Matrix_A)
Matrix_B = np.array([[[24,30,43],[77,56,39],[92,74,87]]])
print(Matrix_B)
# Addition of the Matrix 
Matrix_C = Matrix_A + Matrix_B
print(Matrix_C)

[[[14 36 57]
  [28 67 87]
  [98 76 34]]]
[[[24 30 43]
  [77 56 39]
  [92 74 87]]]
[[[ 38  66 100]
  [105 123 126]
  [190 150 121]]]


In [1]:
# addition og matrix using the list method 
Matrix_A = [[14,36,57],[28,67,87],[98,76,34]]
Matrix_B = [[24,30,43],[77,56,39],[92,74,87]]
Matrix_C = [[0,0,0],[0,0,0],[0,0,0]]
for i in range(3):
    for j in range(3):
        Matrix_C[i][j] = Matrix_A[i][j] + Matrix_B[i][j]
print("Matrix_A")
for row in Matrix_A:
    print(row)
print("Matrix_B")
for row in Matrix_B:
    print(row)
print("Matrix_C")
for row in Matrix_C:
    print(row)

Matrix_A
[14, 36, 57]
[28, 67, 87]
[98, 76, 34]
Matrix_B
[24, 30, 43]
[77, 56, 39]
[92, 74, 87]
Matrix_C
[38, 66, 100]
[105, 123, 126]
[190, 150, 121]
